import React,{useCallback,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,Menu,X,Scissors,MapPin,Phone,Instagram,Plus,Minus,Clock3,ChevronLeft,ChevronRight,MoveUpRight,Check} from 'lucide-react';
import {services,artists,works,faqs,imagePath} from './data';
import {Booking,type BookingSelection} from './Booking';
import {Dialog} from './Dialog';
import './styles.css';
import './studio.css';
const links=[['Services','services'],['Work','work'],['Artists','artists'],['About','about'],['Visit','visit']];
function Wordmark(){return <span className="wordmark">FORMA<span>STUDIO</span></span>}
function App(){
 const [mobile,setMobile]=useState(false),[booking,setBooking]=useState<BookingSelection|null>(null),[filter,setFilter]=useState('All'),[serviceTab,setServiceTab]=useState('Cuts & grooming'),[gallery,setGallery]=useState<number|null>(null),[info,setInfo]=useState<'directions'|'call'|'social'|null>(null),[faq,setFaq]=useState<number|null>(null);
 const closeBooking=useCallback(()=>setBooking(null),[]),closeGallery=useCallback(()=>setGallery(null),[]),closeInfo=useCallback(()=>setInfo(null),[]);
 const book=(service=0,artist='Any available artist')=>{setMobile(false);setBooking({service,artist})};
 const visibleWorks=works.map((w,index)=>({...w,index})).filter(w=>filter==='All'||w.category===filter);
 const moveGallery=useCallback((delta:number)=>setGallery(current=>{const at=visibleWorks.findIndex(w=>w.index===current);return visibleWorks[(at+delta+visibleWorks.length)%visibleWorks.length].index}),[visibleWorks]);
 useEffect(()=>{if(gallery===null)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')moveGallery(-1);if(e.key==='ArrowRight')moveGallery(1)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[gallery,moveGallery]);
 useEffect(()=>{if(!mobile)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMobile(false)};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[mobile]);
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <div className="announcement"><span>GOOD HAIR. YOUR WAY.</span><span>AN INDEPENDENT LOS ANGELES STUDIO <span className="announcement-dot"/></span></div>
 <header className="site-header"><a href="#" aria-label="FORMA Studio home"><Wordmark/></a><nav aria-label="Main navigation" id="main-navigation" className={mobile?'main-nav open':'main-nav'}>{links.map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMobile(false)}>{label}</a>)}<button className="mobile-nav-book" onClick={()=>book()}>Book an Appointment <ArrowUpRight size={16}/></button></nav><button className="button header-book" onClick={()=>book()}>Book an Appointment <ArrowUpRight size={16}/></button><button className="icon-button mobile-toggle" aria-label={mobile?'Close menu':'Open menu'} aria-expanded={mobile} aria-controls="main-navigation" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
 <main id="main">
 <section className="hero studio-hero" aria-labelledby="hero-heading"><div className="hero-composition"><div className="hero-photo"><img src={imagePath('hero')} alt="A softly waved blonde haircut with an effortless, lived-in finish" fetchPriority="high"/></div></div><div className="hero-copy"><p className="eyebrow"><span className="tiny-line"/> INDEPENDENT HAIR STUDIO / LOS ANGELES</p><h1 id="hero-heading">Your hair,<br/>in better <em>form.</em></h1><p className="hero-description">Precision cuts, lived-in color, sharp fades, and effortless styling—created for you in the heart of Los Angeles.</p><div className="hero-actions"><button className="button" onClick={()=>book()}>Book an Appointment <ArrowUpRight size={18}/></button><a className="text-link" href="#work">Explore Our Work <ArrowRight size={17}/></a></div><div className="hero-info"><span><i/> Open Tuesday–Sunday</span><span>Los Angeles, California</span></div></div><div className="hero-bottom-line"><span>CUTS / COLOR / GROOMING / STYLING</span><span>PERSONAL STYLE. EXPERT HANDS.</span></div></section>
 <section className="section services-section" id="services"><div className="section-heading"><div><p className="eyebrow">01 / THE SERVICE MENU</p><h2>Good hair<br/>starts <em>here.</em></h2></div><div className="heading-note"><p>A little maintenance. A whole new mood.<br/>Find what feels right for you.</p><span>CONSIDERED SERVICE. STRAIGHTFORWARD PRICING.</span></div></div><div className="service-tabs" role="tablist" aria-label="Service category">{['Cuts & grooming','Color & styling'].map((tab,i)=><button role="tab" id={`service-tab-${i}`} aria-selected={serviceTab===tab} aria-controls="service-panel" tabIndex={serviceTab===tab?0:-1} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?1:i===0?1:0;setServiceTab(['Cuts & grooming','Color & styling'][next]);document.getElementById(`service-tab-${next}`)?.focus()}}} key={tab} onClick={()=>setServiceTab(tab)}>{tab}<span>0{i+1}</span></button>)}</div><div className="services-layout" id="service-panel" role="tabpanel" aria-labelledby={`service-tab-${serviceTab==='Cuts & grooming'?0:1}`}><div className="service-list">{services.map((s,i)=>s.category===serviceTab&&<article className="service-row" key={s.name}><div><h3>{s.name}</h3><p>{s.description}</p></div><div className="service-price"><span>from <strong>${s.price}</strong></span><button onClick={()=>book(i)} aria-label={`Book This Service: ${s.name}`}><span>Book This Service</span><ArrowUpRight size={18}/></button></div></article>)}</div><div className="service-image"><img src={imagePath(serviceTab==='Cuts & grooming'?'fade':'styling')} alt={serviceTab==='Cuts & grooming'?'Careful beard grooming by a barber':'A stylist creating a fresh blowout for a client'} loading="lazy"/><div><p>More than a haircut.</p><em>A little time for you.</em></div></div></div><div className="service-footnote"><p>Starting prices shown. Final pricing varies with hair length, complexity, and artist.<br/>Every service begins with a conversation. All genders and hair textures welcome.</p><button className="text-link" onClick={()=>book()}>Not sure? Start with a consultation <ArrowUpRight size={16}/></button></div></section>
 <section className="section work-section" id="work"><div className="section-heading"><div><p className="eyebrow">02 / A FEW GOOD HAIR DAYS</p><h2>Fresh work<br/>from the <em>chair.</em></h2></div><p className="heading-note">Different people. Different looks.<br/>The same attention to detail.</p></div><div className="gallery-top"><div className="gallery-filters" aria-label="Filter portfolio">{['All','Cuts','Fades','Color','Styling'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}{f==='All'&&<sup aria-hidden="true">06</sup>}</button>)}</div><span className="gallery-demo">ILLUSTRATIVE STYLE PORTFOLIO</span></div><div className={`work-grid ${filter!=='All'?'filtered':''}`} aria-live="polite">{visibleWorks.map(w=><button className={`work-card work-${w.index}`} key={w.image} onClick={()=>setGallery(w.index)} aria-label={`View ${w.title}`}><div className="work-image"><img src={imagePath(w.image)} alt={w.alt} loading="lazy"/><span className="work-open"><Plus size={23} strokeWidth={1}/></span><span className="work-category">{w.category}</span></div><div className="work-caption"><h3>{w.title}</h3><ArrowUpRight size={16}/></div><p>{w.detail}</p></button>)}</div><div className="work-bottom"><span>INDIVIDUAL EXPRESSION. NO ONE-SIZE-FITS-ALL.</span><button className="text-link" onClick={()=>setInfo('social')}>More from the studio <Instagram size={16}/></button></div></section>
 <section className="about-section" id="about"><div className="about-image"><img src={imagePath('salon')} alt="A calm, contemporary salon interior with uncluttered stations and warm details" loading="lazy"/><span className="image-label">COME AS YOU ARE. LEAVE A LITTLE MORE YOU.</span></div><div className="about-copy"><p className="eyebrow">03 / THE FORMA WAY</p><h2>Neighborhood<br/>energy.<br/><em>Serious craft.</em></h2><p>Good hair starts with being heard.</p><p>FORMA is imagined as an independent LA studio where thoughtful consultations, skilled hands, and good conversation come together. No pressure to fit a look. No complicated salon language.</p><p>Just attention to the details that matter: your texture, your routine, and how you want to feel when you leave the chair.</p><div className="about-values"><span><Check size={15}/> Personal, always</span><span><Check size={15}/> Every texture welcome</span><span><Check size={15}/> Independently minded</span></div><a className="text-link" href="#artists">Meet the people behind the chair <ArrowUpRight size={17}/></a></div></section>
 <section className="section artists-section" id="artists"><div className="section-heading"><div><p className="eyebrow">04 / GOOD HANDS. GOOD PEOPLE.</p><h2>Meet your <em>artists.</em></h2></div><p className="heading-note">Different specialties. One shared approach.<br/>Your style comes first.</p></div><div className="artists-grid">{artists.map(a=><article className="artist-card" key={a.name}><div className={`artist-photo artist-${a.first.toLowerCase()}`}><img src={imagePath(a.image)} alt={`Illustrative portrait for ${a.name}, ${a.specialty.toLowerCase()}`} loading="lazy"/><span>FORMA / {a.first.toUpperCase()}</span></div><div className="artist-name"><h3>{a.name}</h3><span>ARTIST</span></div><p className="artist-specialty">{a.specialty}</p><p className="artist-bio">{a.bio}</p><button className="text-link" onClick={()=>book(a.first==='Nico'?1:a.first==='Jordan'?6:0,a.name)}>Book with {a.first} <ArrowUpRight size={17}/></button></article>)}</div><p className="section-demo">Artist names, profiles, and portraits are illustrative demo content.</p></section>
 <section className="booking-section" id="booking"><div className="booking-overview"><div><p className="eyebrow">YOUR CHAIR IS WAITING</p><h2>A fresh look.<br/><em>A few clicks away.</em></h2><p>Choose your service, find your artist, and make some time for yourself. We’ll start with a conversation.</p><button className="button light" onClick={()=>book()}>Book an Appointment <ArrowUpRight size={17}/></button></div><ol className="booking-steps"><li><span>01</span><div><h3>Find your service</h3><p>A quick refresh or a whole new direction.</p></div><Scissors size={22} strokeWidth={1.2}/></li><li><span>02</span><div><h3>Choose your artist & time</h3><p>The right hands, at the right moment.</p></div><Clock3 size={22} strokeWidth={1.2}/></li><li><span>03</span><div><h3>Make it yours</h3><p>Tell us a little about you. We’re all ears.</p></div><ArrowUpRight size={22} strokeWidth={1.2}/></li></ol></div><div className="integration-note"><div><p className="eyebrow">BUILT TO FIT YOUR BOOKING ROUTINE</p><p>This demo can be adapted to connect with your studio’s existing booking system.</p></div><div className="integration-names"><span>Booksy</span><span>Fresha</span><span>Square Appointments</span><span>Calendly</span><small>Integration examples only · no platforms connected</small></div></div></section>
 <section className="section reviews-section"><p className="eyebrow">SAMPLE CLIENT EXPERIENCES</p><div className="reviews-grid">{[['“For once, I felt like someone really listened to what I wanted. The cut just feels like me.”','ON FEELING HEARD'],['“An easy booking, a warm welcome, and a cut that looks just as good a week later.”','ON THE LITTLE DETAILS'],['“I walked in ready for a change and walked out feeling like myself again. Just a little bolder.”','ON A FRESH START']].map(([quote,caption])=><figure key={caption}><blockquote>{quote}</blockquote><figcaption>{caption}<span>Illustrative testimonial</span></figcaption></figure>)}</div></section>
 <section className="section faq-section" id="faq"><div><p className="eyebrow">BEFORE YOU TAKE A SEAT</p><h2>A few<br/><em>good questions.</em></h2><p>First time? You’re in good company.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div className="faq-item" key={q}><h3><button aria-expanded={faq===i} aria-controls={`faq-answer-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={17}/>:<Plus size={17}/>}</button></h3><div id={`faq-answer-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></section>
 <section className="section visit-section" id="visit"><div className="visit-copy"><p className="eyebrow">05 / OUR CORNER OF LOS ANGELES</p><h2>Come on <em>in.</em></h2><p className="visit-intro">A familiar face. A fresh perspective.<br/>A little space in your day, just for you.</p><div className="visit-details"><div><MapPin size={18}/><p><strong>1428 Forma Avenue</strong>Los Angeles, CA 90026<span>Fictional demonstration address</span></p></div><div><Clock3 size={18}/><div className="hours"><p><span>Tuesday–Friday</span><strong>10 AM–7 PM</strong></p><p><span>Saturday–Sunday</span><strong>10 AM–5 PM</strong></p><p><span>Monday</span><strong>Closed</strong></p></div></div><div><Phone size={18}/><p><button className="inline-link" onClick={()=>setInfo('call')}>(323) 555-0168</button><span>Demo number · not a working line</span></p></div></div><p className="parking-note">In this concept: street parking nearby. Arrive a few minutes early to settle in before your consultation.</p><div className="visit-actions"><button className="button outline" onClick={()=>setInfo('directions')}>Get Directions <ArrowUpRight size={16}/></button><button className="text-link" onClick={()=>setInfo('social')}><Instagram size={16}/> @formastudio.la</button></div></div><div className="location-card"><div className="illustrated-map" aria-label="Illustrative map showing a fictional FORMA Studio location"><div className="map-park park-one"/><div className="map-park park-two"/><span className="map-road road-one">FORMA AVENUE</span><span className="map-road road-two">SUNSET WAY</span><span className="map-neighborhood">LOS ANGELES</span><div className="map-pin"><span>F.</span></div><span className="map-studio">Your good hair<br/><em>starts here.</em></span></div><div className="map-footer"><span>FORMA STUDIO</span><span>Illustrative map · fictional location</span><MoveUpRight size={17}/></div></div></section>
 <section className="closing-section"><img src={imagePath('tools')} alt="Scissors, combs, and grooming tools carefully arranged on a barber’s work surface" loading="lazy"/><div className="closing-copy"><p className="eyebrow">SAME YOU. A FRESH POINT OF VIEW.</p><h2>Ready for your<br/><em>next look?</em></h2><p>Choose your service, select your artist,<br/>and we’ll take it from there.</p><div><button className="button light" onClick={()=>book()}>Book an Appointment <ArrowUpRight size={17}/></button><button className="text-link" onClick={()=>setInfo('call')}>Call the Studio <Phone size={16}/></button></div></div></section>
 </main>
 <footer className="studio-footer"><div className="footer-intro"><a href="#" aria-label="FORMA Studio home"><Wordmark/></a><p>Good hair is personal.<br/>Let’s find your form.</p><button className="button light" onClick={()=>book()}>Find your next look <ArrowUpRight size={18}/></button></div><div className="footer-top"><div className="footer-link-column"><h3>Explore the studio</h3>{links.map(([label,id])=><a href={'#'+id} key={id}>{label}</a>)}</div><div className="footer-hours"><h3>Studio hours</h3><dl><div><dt>Tuesday–Friday</dt><dd>10 AM–7 PM</dd></div><div><dt>Saturday–Sunday</dt><dd>10 AM–5 PM</dd></div><div><dt>Monday</dt><dd>Closed</dd></div></dl></div><div className="footer-contact"><h3>Find us</h3><address>1428 Forma Avenue<br/>Los Angeles, CA 90026</address><p className="footer-small">Fictional demonstration address</p><button onClick={()=>setInfo('call')}>(323) 555-0168 <span>· Demo number</span></button><button onClick={()=>setInfo('social')}><Instagram size={16}/> @formastudio.la <ArrowUpRight size={15}/></button></div></div><div className="footer-bottom"><p>© {new Date().getFullYear()} FORMA Studio. An independent studio concept.</p><a href="#">Back to top <ArrowUpRight size={14}/></a><p className="footer-disclaimer">Concept website created for demonstration purposes. Images and business information are illustrative.</p></div></footer>
 <div className="mobile-action-bar"><button onClick={()=>setInfo('call')}><Phone size={17}/> Call</button><button onClick={()=>setInfo('directions')}><MapPin size={17}/> Directions</button><button onClick={()=>book()}><Scissors size={17}/> Book</button></div>
 {booking&&<Booking initial={booking} onClose={closeBooking}/>}
 {gallery!==null&&<Dialog title={works[gallery].title} onClose={closeGallery} className="gallery-dialog"><div className="lightbox-image"><img src={imagePath(works[gallery].image)} alt={works[gallery].alt}/><button className="gallery-prev icon-button" aria-label="Previous image" onClick={()=>moveGallery(-1)}><ChevronLeft/></button><button className="gallery-next icon-button" aria-label="Next image" onClick={()=>moveGallery(1)}><ChevronRight/></button></div><div className="lightbox-footer"><p>{works[gallery].detail}<span>Illustrative photography · not actual studio work</span></p><button className="text-link" onClick={()=>{setGallery(null);book(works[gallery].category==='Color'?8:works[gallery].category==='Fades'?1:0)}}>Make it your own <ArrowUpRight size={16}/></button></div></Dialog>}
 {info&&<Dialog title={info==='directions'?'A little Los Angeles.':info==='call'?'Let’s talk good hair.':'A glimpse of studio life.'} onClose={closeInfo} className="info-dialog">{info==='directions'?<><MapPin className="info-icon"/><p>1428 Forma Avenue, Los Angeles, CA 90026 is a fictional demonstration address. There is no real salon destination to navigate to.</p><p>For a live studio, this button would open directions to its verified location. The illustrated location card keeps this portfolio concept honest.</p><button className="button" onClick={()=>{setInfo(null);document.getElementById('visit')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}>View studio details <ArrowUpRight size={16}/></button></>:info==='call'?<><Phone className="info-icon"/><p><strong>(323) 555-0168</strong> is an illustrative demo number, not a working studio phone line.</p><p>A live site would let clients call directly. For now, you can try the complete appointment request experience.</p><button className="button" onClick={()=>{setInfo(null);book()}}>Try Demo Booking <ArrowUpRight size={16}/></button></>:<><Instagram className="info-icon"/><p><strong>@formastudio.la</strong> is a placeholder social handle for this fictional studio. It does not link to a real business account.</p><p>Take a look through the style portfolio for a little inspiration instead.</p><button className="button" onClick={()=>{setInfo(null);document.getElementById('work')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}>Explore the work <ArrowUpRight size={16}/></button></>}</Dialog>}
 </>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
