import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowRight, Menu as MenuIcon, X, Plus, Minus, MapPin, Clock3, Phone, Instagram, Check, CalendarDays, ShoppingBag, Sun, Utensils, ChevronDown} from 'lucide-react';
import './styles.css';

type Modal = 'menu'|'order'|'reservation'|'catering'|'directions'|'social'|null;
const dishes = [
 {name:'Crispy Hot Chicken Tacos',price:13,description:'Golden chicken, citrus slaw, comeback sauce. A little heat, a lot to love.',category:'Tacos & more',image:'tacos'},
 {name:'Cielo Smash Burger',price:15,description:'Double smashed beef, melty American, pickles, and our house sauce.',category:'Tacos & more',image:'burger'},
 {name:'Loaded Street Fries',price:11,description:'Crispy fries, queso, pico de gallo, crema, and a little green heat.',category:'Sides & wings',image:'fries'},
 {name:'Citrus Garlic Wings',price:14,description:'Crisp wings tossed in bright citrus, roasted garlic, and fresh herbs.',category:'Sides & wings',image:'wings'},
 {name:'Birria Grilled Cheese',price:14,description:'Slow-braised beef, stretchy cheese, golden sourdough. Consommé on the side.',category:'Tacos & more'},
 {name:'Hibiscus Lime Agua Fresca',price:5,description:'Tart hibiscus, fresh lime, just enough sweetness. Sunshine over ice.',category:'Drinks',image:'drink'}
];
const packages = [{name:'Taco Table',size:10,copy:'Build-your-own tacos, all the fixings, chips & salsa.'},{name:'Wing Night',size:15,copy:'Citrus garlic wings, loaded fries, crunchy slaw & dips.'},{name:'Full Cielo Spread',size:25,copy:'Tacos, wings, fries, sides & aguas frescas. The whole crew, covered.'}];
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const maxDate=()=>{const d=new Date();d.setDate(d.getDate()+60);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function Wordmark(){return <span className="wordmark">cielo<span>STREET KITCHEN</span></span>}
function App(){
 const [modal,setModal]=useState<Modal>(null),[mobile,setMobile]=useState(false),[category,setCategory]=useState('All'),[cart,setCart]=useState<Record<number,number>>({}),[success,setSuccess]=useState(''),[date,setDate]=useState(today()),[time,setTime]=useState(''),[party,setParty]=useState('2'),[selectedPackage,setSelectedPackage]=useState('Taco Table');
 const dialog=useRef<HTMLDivElement>(null); const count=Object.values(cart).reduce((a,b)=>a+b,0); const subtotal=Object.entries(cart).reduce((s,[id,n])=>s+dishes[Number(id)].price*n,0);
 const open=(m:Modal)=>{setSuccess('');setModal(m);setMobile(false);setTime('')};
 useEffect(()=>{if(!modal)return;const prior=document.activeElement as HTMLElement;document.body.style.overflow='hidden';const timer=window.setTimeout(()=>dialog.current?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const els=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input, select, textarea, a[href]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{clearTimeout(timer);document.body.style.overflow='';document.removeEventListener('keydown',key);prior?.focus()}},[modal]);
 const update=(i:number,delta:number)=>setCart(c=>({...c,[i]:Math.max(0,(c[i]||0)+delta)}));
 const slots=['11:00','12:00','13:00','14:00','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30'].filter(t=>date!==today()||t>new Date().toTimeString().slice(0,5));
 const formatTime=(t:string)=>{const [h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`};
 return <>
 <div className="announcement">GOOD FOOD. GOOD COMPANY. VERY LA. <span>YOUR NEW NEIGHBORHOOD FAVORITE <Sun size={13}/></span></div>
 <header><a href="#" aria-label="Cielo home"><Wordmark/></a><nav aria-label="Main navigation" className={mobile?'navigation is-open':'navigation'}>{[['Menu','menu'],['Our Story','story'],['Catering','catering'],['Visit','visit']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMobile(false)}>{label}</a>)}<button className="nav-reserve" onClick={()=>open('reservation')}>Book a Table</button></nav><button className="button header-order" onClick={()=>open('order')}>Order Online <ArrowUpRight size={17}/>{count>0&&<span>({count})</span>}</button><button className="mobile-toggle icon-button" aria-expanded={mobile} aria-label={mobile?'Close navigation':'Open navigation'} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<MenuIcon/>}</button></header>
 <main>
 <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="small-star">✳</span> LOS ANGELES, MEET YOUR NEXT CRAVING</p><h1 id="hero-title">BIG FLAVOR.<br/>ZERO <span className="orange">BORING</span><br/><span className="orange">BITES.</span><span className="hero-spark">✳</span></h1><p className="intro">LA street-food favorites made fresh, stacked high,<br className="desktop-break"/> and served with a little attitude.</p><div className="hero-actions"><button className="button" onClick={()=>open('order')}>Order Online <ArrowUpRight size={18}/></button><a className="text-link" href="#menu">Explore the Menu <ArrowRight size={17}/></a></div><div className="hero-details"><span><i/> Open daily · 11 AM–10 PM</span><span><MapPin size={14}/> Los Angeles, CA</span></div></div><div className="hero-art"><img src="/demos/cielo/images/tacos.jpg" alt="Fresh street tacos with lime, salsa, and colorful toppings on a rustic table" fetchPriority="high"/><div className="photo-shade"/><div className="round-stamp">FRESH MADE.<Sun size={33} strokeWidth={1.3}/>FULL OF SOUL.</div><span className="photo-caption">A LITTLE MESSY. A LOT DELICIOUS.</span><div className="image-note">From our kitchen,<br/><span>with a little LA.</span><svg viewBox="0 0 70 40" aria-hidden="true"><path d="M3 5 Q25 40 63 15 M49 13 L65 14 L59 29" fill="none" stroke="currentColor" strokeWidth="2"/></svg></div></div></section>
 <div className="flavor-strip" aria-label="Street food, Cielo style"><div>STREET FOOD. ELEVATED. <span>✳</span> MADE FRESH. ALWAYS. <span>✳</span> BIG LA ENERGY. <span>✳</span> COME HUNGRY. LEAVE HAPPY. <span>✳</span></div></div>
 <section className="section favorites" id="menu"><div className="section-heading"><div><p className="eyebrow">THE USUALS. ANYTHING BUT ORDINARY.</p><h2>MEET YOUR<br/>NEW FAVORITES<span className="orange">.</span></h2></div><div className="heading-aside"><p>Big cravings, meet your match.<br/>Made to order. Made to hit the spot.</p><button className="text-link" onClick={()=>open('menu')}>View Full Menu <ArrowUpRight size={19}/></button></div></div><div className="featured-grid">{dishes.slice(0,3).map((dish,i)=><article className="food-card" key={dish.name}><button className="food-photo" onClick={()=>open('menu')} aria-label={`Explore ${dish.name}`}><img src={`/demos/cielo/images/${dish.image}.jpg`} alt={i===0?'Street tacos with fresh cilantro and lime':i===1?'Juicy cheeseburger stacked with lettuce and tomato':'Golden fries with savory toppings'} loading="lazy"/>{i===0&&<span className="food-tag">THE CROWD FAVORITE</span>}{i===1&&<span className="food-tag yellow">DOUBLE THE GOOD STUFF</span>}<span className="photo-arrow"><ArrowUpRight size={23}/></span></button><div className="food-title"><h3>{dish.name}</h3><span>${dish.price}</span></div><p>{dish.description}</p>{i===2&&<span className="diet-note">Vegetarian option available</span>}</article>)}</div><div className="more-favorites">{dishes.slice(3).map(d=><button onClick={()=>open('menu')} key={d.name}><span><span className="eyebrow">{d.category}</span><strong>{d.name}</strong></span><span>${d.price} <ArrowUpRight size={16}/></span></button>)}</div></section>
 <section className="story section" id="story"><div className="story-photo"><img src="/demos/cielo/images/interior.jpg" alt="A welcoming neighborhood dining room with warm light and plants" loading="lazy"/><span className="story-photo-label">PULL UP A CHAIR. STAY A WHILE.</span></div><div className="story-copy"><p className="eyebrow">A LITTLE LOCAL LOVE</p><h2>MADE FOR THE<br/>NEIGHBORHOOD<span className="orange">.</span></h2><p>Inspired by the streets of LA. Made for the people who make them special.</p><p>Cielo brings together the flavors we love: crispy, spicy, fresh, and a little unexpected. Think street-food favorites with thoughtful ingredients, generous portions, and zero fuss.</p><p>Lunch break, late dinner, or a table full of your favorite people. There’s a spot for you here.</p><button className="text-link" onClick={()=>open('reservation')}>Good food. Better company. Book a table <ArrowUpRight size={18}/></button></div></section>
 <section className="catering section" id="catering"><div className="catering-top"><div><p className="eyebrow">YOUR PEOPLE. OUR FOOD. ONE GOOD TIME.</p><h2>FEED THE<br/>WHOLE FUNCTION<span>.</span></h2></div><div><p>Office lunches. Birthdays. Student hangouts.<br/>Community gatherings. Whatever brings you<br className="desktop-break"/> together, we’ll bring the flavor.</p><button className="button cream" onClick={()=>open('catering')}>Request Catering <ArrowUpRight size={18}/></button></div></div><div className="catering-grid">{packages.map((p,i)=><button className="package" onClick={()=>{setSelectedPackage(p.name);open('catering')}} key={p.name}><span className="package-number">0{i+1} <ArrowUpRight size={24}/></span><h3>{p.name}</h3><span className="serves">SERVES {p.size}</span><p>{p.copy}</p></button>)}<div className="catering-photo"><img src="/demos/cielo/images/spread.jpg" alt="A generous shared meal with a variety of dishes for a group gathering" loading="lazy"/><span>More seats.<br/>More good stuff.</span></div></div><p className="catering-footnote">A small get-together or a big celebration. We’ll help you make it yours.</p></section>
 <section className="testimonials section"><p className="eyebrow">SAMPLE CUSTOMER EXPERIENCE · ILLUSTRATIVE TESTIMONIALS</p><div className="quote-grid">{[['“Ordered in a few taps. Picked up a bag full of happiness.”','THE LUNCH-BREAK REGULAR'],['“The taco table was the main event. Even at a birthday party.”','THE PARTY PLANNER'],['“Came for the burger. Stayed for the neighborhood feeling.”','THE NEW NEIGHBOR']].map(([q,n])=><figure key={n}><span className="quote-mark">“</span><blockquote>{q.replace(/[“”]/g,'')}</blockquote><figcaption>{n}<span>Sample testimonial</span></figcaption></figure>)}</div></section>
 <section className="visit section" id="visit"><div><p className="eyebrow">YOUR TABLE’S WAITING</p><h2>COME THROUGH<span className="orange">.</span></h2><p className="visit-intro">Good food is even better in good company.</p><div className="visit-info"><div><MapPin size={20}/><p><strong>1842 Cielo Avenue</strong>Los Angeles, CA 90026<span className="muted">Fictional address for this concept</span></p></div><div><Clock3 size={20}/><p><strong>Every day, 11 AM–10 PM</strong>Lunch, dinner & everything in between.</p></div><div><Phone size={20}/><p><a href="tel:+13235550148">(323) 555-0148</a><span className="muted">Demo number · not a working phone line</span></p></div></div><p className="parking">In this concept: street parking nearby and easy pickup at the front counter. Drop in hungry.</p><div className="visit-actions"><button className="button" onClick={()=>open('reservation')}>Book a Table <CalendarDays size={17}/></button><button className="text-link" onClick={()=>open('directions')}>Find us <ArrowUpRight size={17}/></button></div></div><div className="location-card"><div className="map-art" aria-hidden="true"><div className="park park-one"/><div className="park park-two"/><span className="map-street street-one">CIELO AVENUE</span><span className="map-street street-two">SUNSHINE BOULEVARD</span><div className="map-marker"><Utensils size={26}/></div><span className="map-brand">Meet you at cielo.</span><span className="map-area">LOS ANGELES STATE OF MIND</span></div><div className="map-caption"><span>OUR LITTLE CORNER OF LA</span><span>Illustrative map · fictional location</span></div></div></section>
 <section className="final-cta"><img src="/demos/cielo/images/wings.jpg" loading="lazy" alt="Crispy chicken wings ready to share"/><div><p className="eyebrow">FOLLOW YOUR CRAVINGS.</p><h2>HUNGRY YET?</h2><div><button className="button cream" onClick={()=>open('order')}>Order Online <ArrowUpRight size={18}/></button><a className="text-link" href="tel:+13235550148">Call the Restaurant <Phone size={17}/></a></div><small>Demo ordering & phone number</small></div><span className="cta-sun">✳</span></section>
 </main>
 <footer><div className="footer-main"><div><a href="#"><Wordmark/></a><p>Big flavor. Good company.<br/>A little Los Angeles in every bite.</p></div><div><p className="eyebrow">COME HANG</p><a href="#menu">Menu</a><a href="#story">Our Story</a><a href="#catering">Catering</a><button onClick={()=>open('reservation')}>Reservations</button></div><div><p className="eyebrow">FIND US</p><span>1842 Cielo Avenue, Los Angeles</span><span>Open daily · 11 AM–10 PM</span><a href="tel:+13235550148">(323) 555-0148 · Demo</a></div><div><p className="eyebrow">A TASTE OF THE GOOD LIFE</p><button className="social-link" onClick={()=>open('social')}><Instagram size={19}/> @cielostreetkitchen <ArrowUpRight size={16}/></button><span>Illustrative social handle</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Cielo Street Kitchen · A restaurant concept</span><span>Concept website created for demonstration purposes. Images and business information are illustrative.</span></div></footer>
 <div className="mobile-actions"><a href="tel:+13235550148"><Phone size={18}/>Call <small>demo</small></a><button onClick={()=>open('directions')}><MapPin size={18}/>Directions</button><button onClick={()=>open('order')}><ShoppingBag size={18}/>Order{count>0?` (${count})`:''}</button></div>
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className={`modal ${modal==='menu'||modal==='order'?'wide':''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title" ref={dialog} tabIndex={-1}><button className="modal-close icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X/></button><p className="eyebrow">CIELO STREET KITCHEN · DEMO EXPERIENCE</p><h2 id="modal-title">{modal==='reservation'?'SAVE YOUR SEAT.':modal==='catering'?'LET’S FEED YOUR PEOPLE.':modal==='order'?'GOOD FOOD, TO GO.':modal==='menu'?'THE GOOD STUFF.':modal==='directions'?'OUR CORNER OF LA.':'STAY IN THE LOOP.'}</h2>
 {success?<div className="success" role="status"><span className="success-icon"><Check size={30}/></span><h3>{modal==='reservation'?'Your demo table is booked.':modal==='order'?'Your demo order is in.':'Your demo inquiry is ready.'}</h3><p>{success}</p><p className="demo-note">This is a portfolio demonstration. Nothing has been sent, charged, or reserved with a real restaurant.</p><button className="button" onClick={()=>setModal(null)}>Back to Cielo <ArrowRight size={17}/></button></div>:<>
 {(modal==='menu'||modal==='order')&&<><p className="modal-intro">Freshly made, generously served. {modal==='order'?'Build a pickup order and try our demo checkout.':'Your next favorite is right here.'}</p><div className="menu-tabs" aria-label="Filter menu">{['All','Tacos & more','Sides & wings','Drinks'].map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="modal-dishes">{dishes.map((d,i)=>(category==='All'||d.category===category)&&<article key={d.name}>{d.image?<img src={`/demos/cielo/images/${d.image}.jpg`} alt={d.name} loading="lazy"/>:<div className="dish-icon"><Utensils/></div>}<div><h3>{d.name}</h3><p>{d.description}</p><strong>{money(d.price)}</strong></div>{modal==='order'?<div className="quantity"><button aria-label={`Remove one ${d.name}`} disabled={!cart[i]} onClick={()=>update(i,-1)}><Minus size={15}/></button><span aria-live="polite">{cart[i]||0}</span><button aria-label={`Add one ${d.name}`} onClick={()=>update(i,1)}><Plus size={15}/></button></div>:<button className="icon-button add-dish" aria-label={`Order ${d.name}`} onClick={()=>{update(i,1);setModal('order')}}><Plus size={19}/></button>}</article>)}</div><p className="demo-note">Please discuss allergies with the restaurant before ordering. All prices and offerings are illustrative.</p>{modal==='menu'?<button className="button" onClick={()=>setModal('order')}>Start an Order <ArrowRight size={17}/></button>:<form className="checkout" onSubmit={e=>{e.preventDefault();setSuccess(`Thanks! Your ${count}-item pickup order (${money(subtotal)}, before any taxes) is confirmed for this demo. Estimated preparation time: 25–35 minutes.`);setCart({})}}><div className="cart-total"><span>{count} {count===1?'item':'items'} · Subtotal</span><strong>{money(subtotal)}</strong></div><p className="demo-note">Pickup only · Demo subtotal, no taxes or payment collected.</p><div className="form-grid"><label>Name<input required name="name" autoComplete="name" placeholder="Your name" maxLength={100}/></label><label>Email<input required name="email" type="email" autoComplete="email" placeholder="you@example.com"/></label></div><button className="button full" disabled={!count}>Place Demo Order <ArrowRight size={18}/></button></form>}</>}
 {modal==='reservation'&&<><p className="modal-intro">A catch-up, a date night, a just-because dinner. Make yourself at home.</p><form onSubmit={e=>{e.preventDefault();if(!time||!slots.includes(time))return;const data=new FormData(e.currentTarget);setSuccess(`${data.get('name')}, we’ve saved a demo table for ${party} on ${new Date(date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})} at ${formatTime(time)}. Your table is yours for 90 minutes. No confirmation email will be sent.`)}}><div className="form-grid"><label>Date<input type="date" required min={today()} max={maxDate()} value={date} onChange={e=>{setDate(e.target.value);setTime('')}}/></label><label>Party size<span className="select-wrap"><select value={party} onChange={e=>{setParty(e.target.value);setTime('')}}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n} {n===1?'guest':'guests'}</option>)}</select><ChevronDown size={16}/></span></label></div><fieldset className="time-field"><legend>Choose a time <span>Illustrative availability</span></legend><div className="time-slots">{slots.map(t=><label key={t} className={time===t?'selected':''}><input type="radio" name="time" value={t} required checked={time===t} onChange={()=>setTime(t)}/>{formatTime(t)}</label>)}</div>{!slots.length&&<p>No more demo tables today. Please choose another date.</p>}</fieldset><div className="form-grid"><label>Name<input name="name" required autoComplete="name" placeholder="Your name" maxLength={100}/></label><label>Email<input type="email" name="email" required autoComplete="email" placeholder="you@example.com"/></label></div><label>Phone<input type="tel" name="phone" required autoComplete="tel" pattern="[+0-9() .-]{7,25}" placeholder="(323) 555-0123"/></label><label>Anything we should know? <span className="optional">Optional</span><textarea name="notes" placeholder="Accessibility needs, a special occasion…" rows={2} maxLength={1000}/></label><p className="demo-note">Tables for 1–8, up to 60 days ahead. Larger crew? <button type="button" className="inline-link" onClick={()=>open('catering')}>Explore catering.</button> This form simulates a reservation; no real table is booked or personal information stored.</p><button className="button full" disabled={!time}>Confirm Demo Reservation <ArrowRight size={17}/></button></form></>}
 {modal==='catering'&&<><p className="modal-intro">Tell us what you’re planning. We’ll put a little Cielo on the table.</p><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);setSuccess(`Thanks, ${data.get('name')}! Your sample ${selectedPackage} inquiry for ${data.get('guests')} guests is complete. In a live site, our team would follow up with availability and a custom quote.`)}}><div className="form-grid"><label>Name<input required name="name" autoComplete="name" placeholder="Your name"/></label><label>Email<input required name="email" type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Phone<input required name="phone" type="tel" autoComplete="tel" pattern="[+0-9() .-]{7,25}" placeholder="(323) 555-0123"/></label><label>Event date<input required name="date" type="date" min={today()}/></label><label>Estimated guests<input required name="guests" type="number" min="10" max="500" placeholder="25"/></label><label>Package interest<select value={selectedPackage} onChange={e=>setSelectedPackage(e.target.value)}>{packages.map(p=><option key={p.name}>{p.name}</option>)}<option>Help me choose</option></select></label></div><label>Additional details <span className="optional">Optional</span><textarea rows={3} maxLength={2000} placeholder="The occasion, dietary needs, and anything else on your mind…"/></label><p className="demo-note">Demo inquiry only. Personal information is not stored or sent.</p><button className="button full">Send Demo Inquiry <ArrowUpRight size={17}/></button></form></>}
 {modal==='directions'&&<div className="info-dialog"><MapPin size={40}/><h3>1842 Cielo Avenue, Los Angeles</h3><p>Cielo is a fictional restaurant concept. This address and the illustrated map are for demonstration, so there’s no real destination to navigate to.</p><p>In the concept, guests enjoy nearby street parking and convenient pickup at the front counter.</p><button className="button" onClick={()=>{setModal(null);document.getElementById('visit')?.scrollIntoView({behavior:'smooth'})}}>View Visit Details <ArrowRight size={17}/></button></div>}
 {modal==='social'&&<div className="info-dialog"><Instagram size={40}/><h3>A little taste of Cielo.</h3><p>@cielostreetkitchen is an illustrative social handle for this portfolio concept. A live restaurant site would link directly to its Instagram feed here.</p><button className="button" onClick={()=>{setModal(null);document.getElementById('menu')?.scrollIntoView({behavior:'smooth'})}}>Explore the Food <ArrowRight size={17}/></button></div>}
 </>}</div></div>}
 </>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
